# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
name: stratos-backend

services:
  server:
    image: jacopicci/stratos-backend-server
    build:
      context: .
    ports:
      - "0.0.0.0:5371:8000"
    #depends_on:
    #  - db
    environment:
      - DB_HOST=stratosdb-aws.cha6kyqe6mav.eu-central-1.rds.amazonaws.com
      - DB_PORT=5432
      - DB_NAME=stratosDB
      - DB_USER=postgres
      - DB_PASSWORD=Stratos123
      - DJANGO_SETTINGS_MODULE=backendStratos.settings
      - PYTHONUNBUFFERED=1
    # Add a volume mount for development
    volumes:
      - ./backendStratos:/app/backendStratos
    # You can keep the watch section if using Docker Compose v2.22.0+
    develop:
      watch:
        - action: sync
          path: ./backendStratos
          target: /app/backendStratos
          ignore:
            - node_modules/
            - __pycache__/
    # Add healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/debug/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jacopicci@gmail.com
      PGADMIN_DEFAULT_PASSWORD: Stratos
    ports:
      - "5050:80"