# Generated by Django 5.1.5 on 2025-02-04 14:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('body', models.TextField(max_length=10000)),
                ('author', models.CharField(max_length=100)),
                ('creationDate', models.DateField()),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('maxFunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minFunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productionTime', models.IntegerField()),
                ('developers', models.CharField(max_length=1000)),
                ('status', models.IntegerField()),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
