# Generated by Django 5.1.5 on 2025-02-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='membersCount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
