# Generated by Django 5.1.5 on 2025-02-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0003_remove_project_memberscount_stratosuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratosuser',
            name='city',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratosuser',
            name='country',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratosuser',
            name='phone',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratosuser',
            name='state',
            field=models.CharField(default='sd', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stratosuser',
            name='zip',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
