# Generated by Django 5.1.5 on 2025-02-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0005_remove_stratosuser_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
