# Generated by Django 5.1.5 on 2025-03-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0008_alter_stratosuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='isEmailVerified',
            field=models.BooleanField(default=False),
        ),
    ]
