# Generated by Django 5.1.5 on 2025-05-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0009_stratosuser_isemailverified'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='google_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
