# Generated by Django 5.1.5 on 2025-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0010_stratosuser_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='discord_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
