# Generated by Django 5.1.5 on 2025-06-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0017_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='User profile picture (64x64 webp)', null=True, upload_to='profile_pictures/'),
        ),
    ]
