# Generated by Django 5.1.5 on 2025-08-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userModule', '0018_stratosuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stratosuser',
            name='auth0_picture_url',
            field=models.URLField(blank=True, help_text='Profile picture URL provided by Auth0', max_length=500, null=True),
        ),
    ]
