# Generated by Django 5.1.5 on 2025-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('body', models.TextField(max_length=10000)),
                ('author', models.CharField(max_length=100)),
                ('creationDate', models.DateField()),
                ('startingDate', models.DateField()),
                ('endingDate', models.DateField()),
                ('maxFunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minFunds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funds', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productionTime', models.IntegerField()),
                ('developers', models.CharField(max_length=1000)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('file', models.FileField(upload_to='uploads/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
