# Generated by Django 5.1.5 on 2025-03-09 16:57

import backendStratos.utilities
import datetime
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('has_asked_for_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='demo_link',
            field=models.URLField(blank=True, help_text='Link to a playable demo', null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='distribution_platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('xbox_series', 'XBOX SERIES'), ('xbox_one', 'XBOX ONE'), ('ps5', 'PLAY STATION 5'), ('ps4', 'PLAY STATION 4'), ('switch', 'NINTENDO SWITCH'), ('meta_quest', 'META QUEST')], max_length=24), blank=True, default=list, help_text='Select one or more distribution platforms', size=None),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='expected_production_budget',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Production budget in EUR/USD', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 16, 57, 10, 770032, tzinfo=datetime.timezone.utc), help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='i_am_looking_for',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('funding only', 'Funding Only'), ('funding + services', 'Funding + Services'), ('funding + services + hr', 'Funding + Services + HR')], max_length=23), blank=True, default=list, help_text='Describe what you are looking for (e.g., investment, publishing, distribution)', size=None),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='is_debut_title',
            field=models.BooleanField(default=False, help_text='Is this your first (debut) video game title?'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes or details about your project', null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='pitch_password',
            field=models.CharField(blank=True, help_text='Optional password to protect your pitch', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='plan_to_choose_publisher',
            field=models.BooleanField(default=False, help_text='Do you plan on choosing a publisher?'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='project_name',
            field=models.CharField(default='', help_text='Name of the project', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='required_funding_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required funding in EUR/USD', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='trailer_link',
            field=models.URLField(blank=True, help_text='Link to a trailer or gameplay video', null=True),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='name',
            field=models.CharField(help_text='Name of the person submitting', max_length=255),
        ),
    ]
