# Generated by Django 5.1.5 on 2025-03-09 16:58

import backendStratos.utilities
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0002_usercontact_projectsubmission_demo_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 16, 58, 54, 45754, tzinfo=datetime.timezone.utc), help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
    ]
