# Generated by Django 5.1.5 on 2025-03-09 17:10

import backendStratos.utilities
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0003_alter_projectsubmission_expected_release_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercontact',
            name='has_asked_for_contact',
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 17, 10, 55, 522150, tzinfo=datetime.timezone.utc), help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
    ]
