# Generated by Django 5.1.5 on 2025-03-09 17:12

import backendStratos.utilities
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0004_remove_usercontact_has_asked_for_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 9, 17, 12, 15, 293840, tzinfo=datetime.timezone.utc), help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
    ]
