# Generated by Django 5.1.5 on 2025-05-31 10:36

import backendStratos.utilities
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0005_alter_projectsubmission_expected_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 31, 10, 36, 22, 921668, tzinfo=datetime.timezone.utc), help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
    ]
