# Generated by Django 5.1.5 on 2025-06-05 15:42

import backendStratos.utilities
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsModule', '0006_alter_projectsubmission_expected_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='expected_release_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='When do you expect to release?', validators=[backendStratos.utilities.validate_future_date_one_month]),
        ),
    ]
